server:
  port: 8088
spring:
  application:
    name: content-api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_db?serverTimezone=UTC&userUnicode=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 6a68j83j83
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.wusuowei.lgy: debug
    org.springframework: warn